<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
	  
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="LICENSE" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Omen.Controls.Popup.Core.csproj" />
	<ProjectReference Include="..\Application\Omen.Controls.Popup.Application.csproj" />
  </ItemGroup>

</Project>
